List structure
ayebaishmo/ToDoList pull request #1
Opened 2021-12-01 15:19 UTC by ayebaishmo

# In this branch: 
- Use webpack template
- Create index.html file in src folder 
- create index.js file in src folder
- link the files with modules
- create element dynamically with javascript

2021-12-01 20:17 UTC, DeliceLydia requested changes
## Hi @ayebaishmo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 20:17 UTC, DeliceLydia commented on README.md
> +
- [ ] Please add a working link

2021-12-01 20:17 UTC, DeliceLydia commented on README.md
> +- Run the index file on server
- [ ] Add how to get the project up and running locally step by step because when you run `index.html` file only doesn't run and I think `deployment` is not the right place for this. you can add all steps like
- npm i
- npm run build
- npm run start

2021-12-02 08:55 UTC, Emmyn5600 approved these changes
STATUS: APPROVED :+1: 

Hello, @ayebaishmo    👋🏾 👋🏾 congratulations on making it so far on this milestone.

## Optional suggestions

- Check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

2021-12-02 08:55 UTC, Emmyn5600 commented on README.md
Optional, please implement it before you merge.

- [ ] Usage

- Clone repo
-  cd to the repo name
- npm install to install dependencies
- npm start to start the server
- npm test to check the tests.

- [ ] Remove the live link at this moment.

2021-12-02 09:09 UTC, merged