Interactive list
ayebaishmo/ToDoList pull request #2
Opened 2021-12-02 22:55 UTC by ayebaishmo

# In this branch 
- Create different modules
- Add mark interaction to tasks
- Add eventListner checkbox  to mark task
- Enabled change of status of task from true to false, reviser. 
- Add local storage to array of tasks

2021-12-02 23:09 UTC, BrianSammit reviewed
# STATUS: INVALID 🟡 
Hi @ayebaishmo, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 😢 

You have submitted a project, that the linters checks are not working on GitHub.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

![programming-punching-keyboard-coding-anger-13716030304](https://user-images.githubusercontent.com/64173189/131594584-6b633408-f17f-437d-90be-8beb277941ec.gif)


# CHEERS AND HAPPY CODING!! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

Invalid Code Review Request **does not count** into the code reviews limit.

2021-12-03 20:35 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @ayebaishmo,

Good job so far!
✔️ You have descriptive PR
✔️ Your code is nicely modularized
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Your repo contains the `node_modules` folder. This should be correctly ignored by git. Kindly ensure that this folder is not committed to your repo.
![ayeb](https://user-images.githubusercontent.com/36542986/144669323-0884724b-d6d0-4432-adcb-9eba12325597.jpg)

- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 20:35 UTC, TedLivist commented on src/index.js
> +  });
There seem to be some irregularities in the checkbox displays. It does not work properly. Look at the image below
- [ ] For the first image, I checked some tasks as completed and then reloaded the page. After the reload when I click on the checkbox it changes but the strikethrough is gone as evident on the second list item. There should be a strikethrough on the task as long as the box is checked. Kindly fix this behavior.
- [ ] To the second image. When I reload, the completed tasks have expected strikethrough but their checkboxes are not checked. Kindly ensure that checkboxes of completed tasks are correctly checked on page reload.

![ayeb-check](https://user-images.githubusercontent.com/36542986/144665953-f0094b51-d985-43b9-838a-57806b750253.jpg)
![ayeb-check-reload](https://user-images.githubusercontent.com/36542986/144665963-5867fff3-180b-4ed3-bc1a-dd44ce85db69.jpg)

2021-12-03 20:35 UTC, TedLivist commented on src/index.js
>  import './style.css';
- [ ] Let's stick to the design as much as possible. There appear to be some issues with your styling. Kindly style your app as provided in the design template.

![ayeb-design](https://user-images.githubusercontent.com/36542986/144668917-b236db2e-2c34-44a7-927e-8f27952ccf4b.jpg)

2021-12-03 23:12 UTC, HillaryOkello requested changes
# Hi @ayebaishmo , 

## To highlight
✅  You have descriptive PR
✅  Descriptive Readme file
✅  Your code is nicely modularized

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] You still have the node_modules folder in your GitHub repo, to remove it please delete it then push to GitHub then do npm install and push again to Github with the node_modules in .gitignore file.
![interactive](https://user-images.githubusercontent.com/61744527/144684221-bb1e3496-a925-4053-b7b4-321edd76708b.png)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 23:52 UTC, carlos-ssh approved these changes
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi @ayebaishmo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



![Approved](https://user-images.githubusercontent.com/22258274/138466108-6b14c541-6a88-44c5-ba76-c64992ac1835.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 23:52 UTC, carlos-ssh commented on .github/workflows/linters.yml
>    FORCE_COLOR: 1
# 💾 💾 💽 [OPTIONAL]   💽 💾 💾
**✔️ _Keep professionalism in your Repo's_** 
- ⏏︎ Kindly add your `node_modules` to your `.gitignore`.
![Screen Shot 2021-12-03 at 17 44 39](https://user-images.githubusercontent.com/22258274/144687071-d9fd4e41-2c3c-4d6a-9c12-9ea54484df9c.png)

2021-12-04 08:27 UTC, merged